# Generated by Django 4.2.10 on 2024-02-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField(unique=True)),
                ('arrived', models.SmallIntegerField(null=True)),
                ('hosp', models.SmallIntegerField(null=True)),
                ('refused', models.SmallIntegerField(null=True)),
                ('signout', models.SmallIntegerField(null=True)),
                ('deads', models.SmallIntegerField(null=True)),
                ('reanimation', models.SmallIntegerField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dates'], name='data_mainda_dates_2313a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccumulationOfIncoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField(unique=True)),
                ('therapy', models.CharField(max_length=50, null=True)),
                ('surgery', models.CharField(max_length=50, null=True)),
                ('cardiology', models.CharField(max_length=50, null=True)),
                ('urology', models.CharField(max_length=50, null=True)),
                ('neurology', models.CharField(max_length=50, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dates'], name='data_accumu_dates_18d605_idx')],
            },
        ),
    ]
