# Generated by Django 4.2.10 on 2024-04-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannumbers',
            name='active',
        ),
    ]
