# Generated by Django 4.2.10 on 2024-03-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Название профиля'),
        ),
    ]
