# Generated by Django 4.2.10 on 2024-06-12 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDataDetails',
            fields=[
                ('maindata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.maindata')),
                ('registered_patients', models.IntegerField()),
            ],
        ),
    ]
