# Generated by Django 4.2.10 on 2024-06-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_name', models.CharField(max_length=25)),
                ('plan_value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы по пациентам',
                'ordering': ['chart_name'],
            },
        ),
        migrations.CreateModel(
            name='MainDataDetails',
            fields=[
                ('maindata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.maindata')),
                ('registered_patients', models.IntegerField()),
            ],
        ),
    ]
