# Generated by Django 4.2.10 on 2024-04-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_plannumbers_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='KISProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mm.profile_med',
            },
        ),
    ]
