# Generated by Django 4.2.10 on 2024-04-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_kisprofiles'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kisprofiles',
            table='profile_med',
        ),
    ]
