# Generated by Django 4.2.10 on 2024-04-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_kisprofiles_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kisprofiles',
            table='mm.profile_med',
        ),
    ]
