# Generated by Django 4.2.10 on 2024-04-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_kisprofiles_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kisprofiles',
            table='profile_med',
        ),
    ]
