# Generated by Django 5.0.1 on 2024-01-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dates', models.DateField(unique=True)),
                ('arrived', models.SmallIntegerField()),
                ('hosp', models.SmallIntegerField()),
                ('refused', models.SmallIntegerField()),
                ('signout', models.SmallIntegerField()),
                ('deads', models.SmallIntegerField()),
                ('reanimation', models.SmallIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['dates'], name='pg_processi_dates_dfd7af_idx')],
            },
        ),
    ]
