# Generated by Django 5.0.1 on 2024-02-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField(unique=True)),
                ('arrived', models.SmallIntegerField(null=True)),
                ('hosp', models.SmallIntegerField(null=True)),
                ('refused', models.SmallIntegerField(null=True)),
                ('signout', models.SmallIntegerField(null=True)),
                ('deads', models.SmallIntegerField(null=True)),
                ('reanimation', models.SmallIntegerField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dates'], name='pg_processi_dates_dfd7af_idx')],
            },
        ),
    ]
