# Generated by Django 5.0.1 on 2024-02-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='arrived',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='maindata',
            name='deads',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='maindata',
            name='hosp',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='maindata',
            name='reanimation',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='maindata',
            name='refused',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='maindata',
            name='signout',
            field=models.SmallIntegerField(null=True),
        ),
    ]
