# Generated by Django 4.2.10 on 2024-04-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KISProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название профиля')),
            ],
            options={
                'verbose_name': 'Профиль КИСа',
                'verbose_name_plural': 'Профили КИСа',
                'db_table': 'profile_med',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
