# Generated by Django 4.2.10 on 2024-04-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_kis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kisprofiles',
            options={'managed': False, 'ordering': ['name'], 'verbose_name': 'Профиль КИСа', 'verbose_name_plural': 'Профили КИСа'},
        ),
    ]
